### ISSUE TITLE
dependency on ruby-mqtt git branch blocks publication to rubygems.org

### ISSUE THREAD

**Issue by shadowbq** [jbarlow-mcafee/opendxl-client-ruby#2]
Please start preparing the gem requirements for public consumption.

Installing a gem `mqtt` directly from a git repository (non master branch) is a feature of Bundler, not a feature of RubyGems.  Bunder is an app tool, and development cycle tool, not to be used when there are upstream requirements. (opendxl-client-ruby will be included as a dependency in other gems)

https://github.com/camlow325/ruby-mqtt/tree/dxl-changes

Applications can be released with git branch requirements, but a core library like opendxl-client-ruby needs to be able to be pinned (or tilda/approximately greater than) to released versions.

In order to release a gem, all its dependencies must also be released as gems.

reference: https://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

**Comment by jbarlow-mcafee** [comment]
Thanks for the note. In d4eec63, I added a pin at 0.5.0 of the `mqtt` gem which was released to Rubygems.
